# GitBook Configuration
root: ./content

structure:
  readme: README.md
  summary: SUMMARY.md

# Redirects (add as needed)
redirects: {}

# PDF export settings
# Note: PDF export must be enabled in GitBook dashboard settings

# Branding Configuration
# Note: Most branding (logo, colors, themes) is configured through the GitBook dashboard:
# Dashboard → Space Settings → Appearance

# GitBook metadata (useful for SEO and branding)
metadata:
  title: "DeFi University - Beginner DeFi Concepts Course"
  description: "Master foundational DeFi concepts, blockchain infrastructure, wallets, security, and financial primitives"

# Links (configure in dashboard for header/footer)
# These are configured in: Dashboard → Space Settings → Appearance → Header & Footer

# Variables for consistent branding
variables:
  university_name: "DeFi University"
  course_name: "Beginner DeFi Concepts Course"

